# logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{0}] - %msg%n'
  level:
    com.github.kmandalas.aodm.impressions.producer: DEBUG
# kafka
spring:
  kafka:
    bootstrap-servers: http://127.0.0.1:9092
    template:
      default-topic: impressions-test