DROP TABLE IF EXISTS accounts;

CREATE TABLE accounts (
  id int(11) NOT NULL AUTO_INCREMENT,
  ad_group_id int(11) NOT NULL,
  ad_group_name varchar(100),
  actual_spend 	double,
  in_flight_spend double,
  daily_budget double,
  item_price double,
  PRIMARY KEY (id)
);

-- CREATE TABLE accounts_AUD (
-- 	id BIGINT NOT NULL,
--     REV INTEGER NOT NULL,
--     REVTYPE TINYINT,
--     ad_group_id int(11) NOT NULL,
--     ad_group_name varchar(100),
--     actual_spend double,
--     in_flight_spend double,
--     daily_budget double,
--     item_price double,
--     PRIMARY KEY (id, REV)
-- );
--
-- CREATE TABLE revinfo (
--     rev INTEGER GENERATED BY DEFAULTAS IDENTITY (START WITH 1),
--     revtstmp BIGINT,
--     PRIMARY KEY (rev)
-- );
--
-- ALTER TABLE accounts_aud
-- ADD CONSTRAINT
--     fkllaf9w93qaiooguo8mfvwtwbg
-- FOREIGN KEY ( REV ) REFERENCES revinfo

insert into accounts(id, ad_group_id, ad_group_name, actual_spend, in_flight_spend, daily_budget, item_price) values(1, 100, 'Alpha SA', 0, 0, 500, 0.20);
insert into accounts(id, ad_group_id, ad_group_name, actual_spend, in_flight_spend, daily_budget, item_price) values(2, 101, 'Beta LTD', 0, 0, 500, 0.20);
insert into accounts(id, ad_group_id, ad_group_name, actual_spend, in_flight_spend, daily_budget, item_price) values(3, 102, 'Gamma SRL', 0, 0, 500, 0.20);
insert into accounts(id, ad_group_id, ad_group_name, actual_spend, in_flight_spend, daily_budget, item_price) values(4, 103, 'Delta SA', 0, 0, 500, 0.20);
insert into accounts(id, ad_group_id, ad_group_name, actual_spend, in_flight_spend, daily_budget, item_price) values(5, 104, 'Epsilon LTD', 0, 0, 500, 0.20);
